# -*- coding: utf-8 -*-
"""ocr_and_classify_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jpbj52IyF2Q9CJIBcDwKoK-YEY48H8dY
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# ! git clone https://github.com/PraeJi/OCR_with_Qwen2VLModel.git

from OCR_with_Qwen2VLModel.ocr_and_classifycontent_qwenmodel import ocr_and_classify

from PIL import Image
import json
import gradio as gr

def result_json(img_path):
    img = Image.open(img_path)
    result_txt = ocr_and_classify(img)
    result_clean = result_txt.replace("```","").replace("json","")
    result_all = json.loads(result_clean)
    result_all["เบอร์โทร"] = result_all["เบอร์โทร"].replace(" ",", ")
    return result_all

# img_test = "/kaggle/input/image-for-test-ocr/588497508_26033068199629460_2091224368113351131_n.jpg"
# test = result_json(img_test)
# test

with gr.Blocks() as Demo:
    with gr.Row():
        with gr.Column():
            input_image = gr.Image(type="filepath")
            with gr.Row():
                btn_clear = gr.ClearButton(components=[input_image])
                btn = gr.Button("Submit", variant="primary")
        with gr.Column():
            name = gr.Textbox(label="ชื่อ Account")
            addr = gr.Textbox(label="ที่อยู่")
            details = gr.TextArea(label="ข้อมูลที่ขอความช่วยเหลือ")
            type_help = gr.Textbox(label="ประเภทความช่วยเหลือ")
            calls = gr.Textbox(label="เบอร์โทร")

    def process(input_image):
        try:
            result = result_json(input_image)
            return result["ชื่อ Account"], result["ที่อยู่"], result["ข้อมูลที่ขอความช่วยเหลือ"], result["ประเภทความช่วยเหลือ"], result["เบอร์โทร"]
        except Exception as e:
            err = "เกิดข้อผิดพลาด กรุณาตรวจสอบรูปภาพ"
            return err, err, err, err, err

    btn.click(
            fn = process,
            inputs = input_image,
            outputs = [name, addr, details, type_help, calls],
        )

Demo.launch(share=True)

